import os
import json
from datetime import datetime, timezone
from pymongo import MongoClient
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ==========================================
# Database Connection Setup
# ==========================================
uri = os.getenv("MONGODB_URI")
if not uri:
    # Fallback to localhost if MONGODB_URI is not set in the environment variables
    uri = "mongodb://localhost:27017/"

client = MongoClient(uri)
db = client["medilogue_db"]

# ==========================================
# Collections Definition
# ==========================================
dialect_collection = db["dialect_glossary"]
intake_logs_collection = db["patient_intakes"]

# ==========================================
# Core Database Functions
# ==========================================

def get_dialect_meaning(term: str) -> str:
    """
    Searches the database for the clinical meaning of a specific Sabah dialect term 
    to enrich the AI agent's contextual understanding.
    
    Args:
        term (str): The local dialect word/phrase (e.g., 'ampus', 'ngilu').
        
    Returns:
        str: A JSON-formatted string containing the term and its clinical mapping.
    """
    if not term:
        return json.dumps({"error": "No term provided."})
    
    # Perform a case-insensitive and stripped search
    result = dialect_collection.find_one({"dialect": term.lower().strip()})
    
    if result:
        return json.dumps({
            "term": term, 
            "meaning": result.get("meaning", "No clinical mapping found in database.")
        })
        
    return json.dumps({
        "term": term, 
        "meaning": "Term not found in the local dialect database glossary."
    })

def save_clinical_intake(patient_input: str, vitals: dict, ai_summary: str) -> str:
    """
    Persists the clinically translated referral logs generated autonomously by the AI agent.
    
    Args:
        patient_input (str): The raw complaint directly from the patient.
        vitals (dict): Dictionary containing vital signs (e.g., heart rate, blood pressure).
        ai_summary (str): The structured clinical translation generated by the Qwen engine.
        
    Returns:
        str: A JSON-formatted string indicating transaction success or failure.
    """
    try:
        document = {
            "timestamp": datetime.now(timezone.utc),  # Using standard modern timezone-aware UTC datetime
            "patient_complaint_raw": patient_input,
            "vitals": vitals,
            "clinical_summary_generated": ai_summary
        }
        result = intake_logs_collection.insert_one(document)
        return json.dumps({
            "status": "success", 
            "inserted_id": str(result.inserted_id)
        })
    except Exception as e:
        return json.dumps({
            "status": "error", 
            "message": f"Failed to save clinical intake. Details: {str(e)}"
        })